model_path: ./models/model.pkl

gym_data_name: hietaniemi-gym-data.csv

weather_data_name: kaisaniemi-weather-data.csv

device_mapping:
    19: etupenkki
    20: ojentajapunnerrus
    21: vinopenkkipunnerrus
    22: hauiskaanto
    23: penkkipunnerrus
    24: ylaveto
    25: jalkakyykky
    26: soutulaite
